services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gitspatch
      POSTGRES_PASSWORD: gitspatch
      POSTGRES_DB: gitspatch
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
