site_name: Gitspatch
site_description: Connect any webhook to GitHub Actions

repo_url: https://github.com/gitspatch/gitspatch
repo_name: gitspatch/gitspatch

theme:
    name: material
    logo: assets/logo.svg
    font:
      text: Inter
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: custom
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: custom
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.12/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - gitspatch

nav:
  - About: index.md
