"""Add SaaS properties

Revision ID: e2d6a1933e83
Revises: 9e62100c226e
Create Date: 2024-12-30 10:33:54.964014

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2d6a1933e83"
down_revision: str | None = "9e62100c226e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gitspatch_users", sa.Column("max_webhooks", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE gitspatch_users SET max_webhooks = 1")
    op.alter_column("gitspatch_users", "max_webhooks", nullable=False)

    op.add_column(
        "gitspatch_users", sa.Column("webhooks_benefit_id", sa.String(), nullable=True)
    )
    op.add_column(
        "gitspatch_users", sa.Column("customer_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gitspatch_users", "customer_id")
    op.drop_column("gitspatch_users", "webhooks_benefit_id")
    op.drop_column("gitspatch_users", "max_webhooks")
    # ### end Alembic commands ###
