"""Fix WebhookEvent.workflow_run_id type

Revision ID: 5b8591cf5a91
Revises: 54c1023e3ea5
Create Date: 2024-12-15 15:36:50.419839

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b8591cf5a91"
down_revision: str | None = "54c1023e3ea5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gitspatch_webhook_events",
        "workflow_run_id",
        existing_type=sa.VARCHAR(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gitspatch_webhook_events",
        "workflow_run_id",
        existing_type=sa.BigInteger(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
