"""Add User and UserSession

Revision ID: 4f1acfc2225c
Revises:
Create Date: 2024-11-11 14:53:52.489801

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f1acfc2225c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gitspatch_users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("github_account_id", sa.String(), nullable=False),
        sa.Column("github_token", sa.JSON(), nullable=False),
        sa.Column("id", sa.CHAR(length=14), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gitspatch_users")),
    )
    op.create_index(
        op.f("ix_gitspatch_users_created_at"),
        "gitspatch_users",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gitspatch_users_updated_at"),
        "gitspatch_users",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "gitspatch_user_sessions",
        sa.Column("user_id", sa.CHAR(length=14), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.CHAR(length=14), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["gitspatch_users.id"],
            name=op.f("fk_gitspatch_user_sessions_user_id_gitspatch_users"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gitspatch_user_sessions")),
    )
    op.create_index(
        op.f("ix_gitspatch_user_sessions_created_at"),
        "gitspatch_user_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gitspatch_user_sessions_expires_at"),
        "gitspatch_user_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gitspatch_user_sessions_token"),
        "gitspatch_user_sessions",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_gitspatch_user_sessions_updated_at"),
        "gitspatch_user_sessions",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "gitspatch_webhooks",
        sa.Column("user_id", sa.CHAR(length=14), nullable=False),
        sa.Column("github_repository_id", sa.BigInteger(), nullable=False),
        sa.Column("github_workflow_id", sa.String(), nullable=False),
        sa.Column("github_installation_id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("id", sa.CHAR(length=14), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["gitspatch_users.id"],
            name=op.f("fk_gitspatch_webhooks_user_id_gitspatch_users"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gitspatch_webhooks")),
    )
    op.create_index(
        op.f("ix_gitspatch_webhooks_created_at"),
        "gitspatch_webhooks",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gitspatch_webhooks_token"),
        "gitspatch_webhooks",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_gitspatch_webhooks_updated_at"),
        "gitspatch_webhooks",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_gitspatch_webhooks_updated_at"), table_name="gitspatch_webhooks"
    )
    op.drop_index(op.f("ix_gitspatch_webhooks_token"), table_name="gitspatch_webhooks")
    op.drop_index(
        op.f("ix_gitspatch_webhooks_created_at"), table_name="gitspatch_webhooks"
    )
    op.drop_table("gitspatch_webhooks")
    op.drop_index(
        op.f("ix_gitspatch_user_sessions_updated_at"),
        table_name="gitspatch_user_sessions",
    )
    op.drop_index(
        op.f("ix_gitspatch_user_sessions_token"), table_name="gitspatch_user_sessions"
    )
    op.drop_index(
        op.f("ix_gitspatch_user_sessions_expires_at"),
        table_name="gitspatch_user_sessions",
    )
    op.drop_index(
        op.f("ix_gitspatch_user_sessions_created_at"),
        table_name="gitspatch_user_sessions",
    )
    op.drop_table("gitspatch_user_sessions")
    op.drop_index(op.f("ix_gitspatch_users_updated_at"), table_name="gitspatch_users")
    op.drop_index(op.f("ix_gitspatch_users_created_at"), table_name="gitspatch_users")
    op.drop_table("gitspatch_users")
    # ### end Alembic commands ###
