name: Website Demo

on:
  workflow_dispatch:
    inputs:
      webhook_event_id:
        description: 'Event ID from Gitspatch'
        required: true
      webhook_event_payload:
          description: 'Original webhook payload as string'
          required: false

permissions:
  contents: write
  id-token: write

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Report Workflow Run
        id: workflow-run
        run: |
          # retrieve the ambient OIDC token
          resp=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gitspatch")
          oidc_token=$(jq -r '.value' <<< "${resp}")
          curl -X POST https://b06203f76217.ngrok.app/action/workflow-run -H "Authorization: Bearer ${oidc_token}" -d "{\"event_id\": \"${{ github.event.inputs.webhook_event_id }}\"}"
      - name: Hello ${{ fromJSON(github.event.inputs.webhook_event_payload).name }}
        run: echo "Hello ${{ fromJSON(github.event.inputs.webhook_event_payload).name }}"
