name: Website Demo

on:
  workflow_dispatch:
    inputs:
      webhook_event_id:
        description: 'Event ID from Gitspatch'
        required: true
      webhook_event_payload:
          description: 'Original webhook payload as string'
          required: false

permissions:
  contents: write
  id-token: write

jobs:
  demo:
    name: Hello ${{ fromJSON(github.event.inputs.webhook_event_payload).name }}
    runs-on: ubuntu-latest

    steps:
      - uses: gitspatch/action@main
        id: gitspatch
        with:
          event_id: ${{ github.event.inputs.webhook_event_id }}
          event_payload: ${{ github.event.inputs.webhook_event_payload }}
      - name: Hello ${{ fromJSON(github.event.inputs.webhook_event_payload).name }}
        run: echo "Hello ${{ fromJSON(github.event.inputs.webhook_event_payload).name }}"
